### ISSUE TITLE
Python Implementation

### ISSUE THREAD

**Issue by Dadatata-JZ** [fcdimitr/sgtsnepi#3]
The new algo looks really promising. Is it possible to be implemented with python? I saw many pre-required c++ libs. Is there any plan to make it work? Or it would be theoretically very HARD. Thanks

**Comment by pitsianis** [comment]
Thank you!

We have no plan to provide a python implementation. I recommend you call the binary from python. See the [instructions](https://github.com/fcdimitr/sgtsnepi#support-of-the-conventional-t-sne) so that it will work with all the corresponding [scripts](https://github.com/lvdmaaten/bhtsne/) provided by Laurens van der Maarten.

The only drawback is that the input and output parameters are passed via the file system. 

Alternatively, we can provide the interface and a shared library that can be called from python or any language that has a foreign function calling capability. We will need (your?) help for that.
